on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nuget package version"
        required: true
        type: string
        default: "1.3.0"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Pack nuget package
        run: dotnet pack ./src/Testing.Autofac.sln -c Release -p:Version=${{ inputs.Version }} -o "./build"

      - name: Push to nuget
        run: dotnet nuget push .\build\*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
